import { NotebookData } from './openaiIntegration';

export interface JupyterNotebookFormat {
  cells: Array<Record<string, unknown>>;
  metadata: Record<string, unknown>;
  nbformat: number;
  nbformat_minor: number;
}

export function buildJupyterNotebook(
  notebookData: NotebookData,
  projectName: string
): JupyterNotebookFormat {
  const metadata = notebookData.metadata ?? {
    kernelspec: {
      display_name: 'Python 3',
      language: 'python',
      name: 'python3'
    },
    language_info: {
      name: 'python',
      version: '3.10.0'
    }
  };

  const baseCell = {
    cell_type: 'markdown',
    metadata: {},
    source: [
      `# ${projectName}\n`,
      'Generated by Academic Lab Advisor.\n'
    ]
  };

  return {
    cells: [baseCell, ...notebookData.cells],
    metadata,
    nbformat: notebookData.nbformat ?? 4,
    nbformat_minor: notebookData.nbformat_minor ?? 5
  };
}
